export class userListDB {
    static list_user = [
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Zhi Hean",
            lName: "Cheah",
            email: "b1700593@helplive.edu.my",
            gender: "Male",
            mobile: "010-3592573",
            dob: "17-04-1997",
            location: "Kuala Lumpur",
            last_login: "1 Day ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Jing Li",
            lName: "Lo",
            email: "b1600352@helplive.edu.my",
            gender: "Male",
            mobile: "016-9385394",
            dob: "08-02-1999",
            location: "Selangor",
            last_login: "1 Day ago",
            role: "Seller",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Chun Yin",
            lName: "Chow",
            email: "chowCY@helplive.edu.my",
            gender: "Male",
            mobile: "012-5633746",
            dob: "25-04-1987",
            location: "Kuala Lumpur",
            last_login: "1 Day ago",
            role: "Seller",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Jia Jia",
            lName: "Tan",
            email: "b1503483@helplive.edu.my",
            gender: "Female",
            mobile: "012-5789305",
            dob: "12-06-1999",
            location: "Selangor",
            last_login: "1 Day ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Li Xin",
            lName: "Chen",
            email: "b1803583@helplive.edu.my",
            gender: "Female",
            mobile: "012-4829463",
            dob: "21-07-2000",
            location: "Kuala Lumpur",
            last_login: "1 Day ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Xin Lin",
            lName: "Chai",
            email: "b1700381@helplive.edu.my",
            gender: "Female",
            mobile: "010-58395024",
            dob: "02-09-1997",
            location: "Kuala Lumpur",
            last_login: "1 Day ago",
            role: "Seller",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Mian Kiat",
            lName: "Chin",
            email: "chinMK@helplive.edu.my",
            gender: "Male",
            mobile: "016-48603959",
            dob: "28-10-1978",
            location: "Selangor",
            last_login: "2 Days ago",
            role: "Seller",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Wen Ying",
            lName: "Siw",
            email: "SiwWY@helplive.edu.my",
            gender: "Female",
            mobile: "019-6903883",
            dob: "15-04-1979",
            location: "Selangor",
            last_login: "2 Days ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Kit Heng",
            lName: "Chan",
            email: "b1601646@helplive.edu.my",
            gender: "Male",
            mobile: "013-5839583",
            dob: "20-12-2001",
            location: "Kuala Lumpur",
            last_login: "2 Days ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Kok Wai",
            lName: "Woo",
            email: "b1702454@helplive.edu.my",
            gender: "Male",
            mobile: "010-1695994",
            dob: "30-01-2000",
            location: "Kuala Lumpur",
            last_login: "2 Days ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Kok Kheong",
            lName: "Cheong",
            email: "b1807737@helplive.edu.my",
            gender: "Male",
            mobile: "010-4958204",
            dob: "15-09-1997",
            location: "Kuala Lumpur",
            last_login: "2 Days ago",
            role: "Seller",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Mei Hui",
            lName: "Lee",
            email: "b1713955@helplive.edu.my",
            gender: "Female",
            mobile: "012-4492058",
            dob: "22-08-1998",
            location: "Kuala Lumpur",
            last_login: "2 Days ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Tzia Xin",
            lName: "Tan",
            email: "b1804935@helplive.edu.my",
            gender: "Female",
            mobile: "018-4830583",
            dob: "04-06-1998",
            location: "Kuala Lumpur",
            last_login: "2 Days ago",
            role: "Buyer",
        },
        {
            avatar: "<img src='assets/images/dashboard/profile.png' class='imgTable'>",
            fName: "Wei Lin",
            lName: "Yeat",
            email: "b1700503@helplive.edu.my",
            gender: "Female",
            mobile: "012-5893533",
            dob: "17-04-1999",
            location: "Kuala Lumpur",
            last_login: "3 Days ago",
            role: "Buyer",
        },
    ]
}
