export class orderDB {
    static list_order = [
        {
            "order id": "#51240",
            "product": "PINENG Power Bank",
            "quantity": "1",
            "payment method": "Online Banking",
            "payment status": "<span class='badge badge-warning'>Awaiting Authentication</span>",
            "date": "24-10-2020",
            "total": "RM 104.95",
            "order status": "<span class='badge badge-warning'>Processing</span>",
        },
        {
            "order id": "#51233",
            "product": "USB-C Fast Charger",
            "quantity": "2",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "15-10-2020",
            "total": "RM 67.45",
            "order status": "<span class='badge badge-danger'>Shipped</span>",
        },
        {
            "order id": "#51227",
            "product": "Iphone X Case",
            "quantity": "1",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "07-10-2020",
            "total": "RM 32.60",
            "order status": "<span class='badge badge-danger'>Shipped</span>",
        },
        {
            "order id": "#51221",
            "product": "Anti-BlueRay Screen Protector",
            "quantity": "3",
            "payment method": "GrabPay",
            "payment status": "<span class='badge badge-primary'>Payment Failed</span>",
            "date": "01-10-2020",
            "total": "RM 12.90",
            "order status": "<span class='badge badge-primary'>Cancelled</span>",
        },
        {
            "order id": "#51219",
            "product": "Iphone 11 Clear Tempered Class",
            "quantity": "1",
            "payment method": "Online Banking",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "19-09-2020",
            "total": "RM 23.74",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51214",
            "product": "Reebook Twin-Colour Socks",
            "quantity": "2",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "14-09-2020",
            "total": "RM 87.65",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51202",
            "product": "Mi Air Humidifier",
            "quantity": "1",
            "payment method": "Credit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "22-08-2020",
            "total": "RM 45.30",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51193",
            "product": "Anti-BlueRay Screen Protector",
            "quantity": "2",
            "paymeny method": "Debit Card",
            "payment status": "<span class='badge badge-primary'>Payment Failed</span>",
            "date": "21-08-2020",
            "total": "RM 29.60",
            "order status": "<span class='badge badge-primary'>Cancelled</span>",
        },
        {
            "order id": "#51190",
            "product": "USB-C Fast Charger",
            "quantity": "1",
            "payment method": "GrabPay",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "20-08-2020",
            "total": "RM 15.80",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51188",
            "product": "Portable Laptop Case",
            "quantity": "1",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "02-08-2020",
            "total": "RM 39.90",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51175",
            "product": "Easy clip on USB fan",
            "quantity": "1",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "19-07-2020",
            "total": "RM 35.20",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51168",
            "product": "Smart Card Wallet",
            "quantity": "3",
            "paymeny method": "Online Banking",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "15-07-2020",
            "total": "RM 45.30",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51152",
            "product": "Mi Humidifier",
            "quantity": "2",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-primary'>Payment Failed</span>",
            "date": "27-06-2020",
            "total": "RM 28.20",
            "order status": "<span class='badge badge-primary'>Cancelled</span>",
        },
        {
            "order id": "#51151",
            "product": "USB-C Fast Charger",
            "quantity": "1",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "17-06-2020",
            "total": "RM 17.90",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
        {
            "order id": "#51145",
            "product": "Anti-BlueRay Screen Protector",
            "quantity": "1",
            "payment method": "Debit Card",
            "payment status": "<span class='badge badge-success'>Paid</span>",
            "date": "09-06-2020",
            "total": "RM 10.90",
            "order status": "<span class='badge badge-success'>Delivered</span>",
        },
    ]
}
